server:
  port: 8085

spring:
  datasource:
    url: jdbc:h2:mem:followdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
#server:
#  port: 8081
#
#spring:
#  application:
#    name: follow-service
#  datasource:
#    url: jdbc:h2:mem:follow
#    driver-class-name: org.h2.Driver
#    username: admin
#    password: password
#  h2:
#    console:
#      enabled: true
#      path: /h2-console # if we navigate to localhost:8081/h2-console, we will see the console
  jpa:
    hibernate:
      ddl-auto: update # tables will be updated based on our entities (created if doesn't exist yet)
    properties:
      hibernate:
        format_sql: true # see SQL statements printed/formatted in our terminal
  cloud:
    consul:
<<<<<<< HEAD
      enabled: true # This takes a bit of set up, will do this later
=======
      enabled: false # This takes a bit of set up, will do this later
>>>>>>> 37f76713933f2d99cc9de867b071f1e76270d34e
    config:
      enabled: false

# Set up/enable some actuator endpoints:
management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: your-super-secret-key-must-be-at-least-256-bits-long-change-this-in-production
