server:
  port: 8084
spring:
  application:
    name: ComReactService
  cloud:
    config:
      enabled: false
    consul:
      enabled: true
  datasource:
    url: jdbc:h2:mem:comreact
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

profile-service:
  url: http://localhost:8082

post-service:
  url: http://localhost:8083