#server:
#  port: 8080
#
#spring:
#  application:
#    name: workshop-service
#  datasource:
#    url: jdbc:h2:mem:workshops
#    driver-class-name: org.h2.Driver
#    username: postgres
#    password: password123
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#  cloud:
#    consul:
#      enabled: false
#    config:
#      enabled: false
#
##Set up/enable some actuator endpoints:
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info