server:
<<<<<<< HEAD
<<<<<<< HEAD
  port: 8081
=======
  port: 8080
>>>>>>> 37f76713933f2d99cc9de867b071f1e76270d34e
=======
  port: 8080
>>>>>>> 37f76713933f2d99cc9de867b071f1e76270d34e

spring:
  application:
    name: AuthService
  datasource:
    url: jdbc:h2:mem:auth
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  cloud:
    consul:
<<<<<<< HEAD
<<<<<<< HEAD
      enabled: true
=======
      enabled: false
>>>>>>> 37f76713933f2d99cc9de867b071f1e76270d34e
=======
      enabled: false
>>>>>>> 37f76713933f2d99cc9de867b071f1e76270d34e
    config:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: your-super-secret-key-must-be-at-least-256-bits-long-change-this-in-production